"""Update goods table with primary_category and subcategory

Revision ID: 0370049bd295
Revises: 4aa1f8703da7
Create Date: 2026-01-26 11:09:28.011212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0370049bd295'
down_revision: Union[str, Sequence[str], None] = '4aa1f8703da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_building_blueprints_id'), table_name='building_blueprints')
    op.drop_table('building_blueprints')
    op.add_column('goods', sa.Column('primary_category', sa.String(), nullable=False))
    op.add_column('goods', sa.Column('subcategory', sa.String(), nullable=True))
    op.alter_column('goods', 'rarity',
               existing_type=postgresql.ENUM('common', 'rare', 'exotic', name='goodsrarity'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('ix_goods_name'), table_name='goods')
    op.create_unique_constraint(None, 'goods', ['name'])
    op.drop_column('goods', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('category', postgresql.ENUM('energy', 'metal', 'organic', 'gaseous', 'chemical', 'exotic', 'biotech', name='goodscategory'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goods', type_='unique')
    op.create_index(op.f('ix_goods_name'), 'goods', ['name'], unique=True)
    op.alter_column('goods', 'rarity',
               existing_type=sa.String(),
               type_=postgresql.ENUM('common', 'rare', 'exotic', name='goodsrarity'),
               existing_nullable=False)
    op.drop_column('goods', 'subcategory')
    op.drop_column('goods', 'primary_category')
    op.create_table('building_blueprints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('max_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('base_efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('energy_production', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('energy_consumption', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('operating_cost', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('supported_goods', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('production_recipes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('construction_cost', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('building_blueprints_pkey'))
    )
    op.create_index(op.f('ix_building_blueprints_id'), 'building_blueprints', ['id'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blueprint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('owner_company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'constructing'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_capacity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('current_efficiency', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'1'::double precision"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['building_blueprints.id'], name=op.f('buildings_blueprint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('buildings_pkey'))
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    # ### end Alembic commands ###
