"""add_tilemap_support_to_locations

Revision ID: 13b8d6bf1310
Revises: 2f10935f78d2
Create Date: 2026-01-27 08:36:54.707387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13b8d6bf1310'
down_revision: Union[str, Sequence[str], None] = '2f10935f78d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('grid_width', sa.Integer(), nullable=False))
    op.add_column('locations', sa.Column('grid_height', sa.Integer(), nullable=False))
    op.add_column('locations', sa.Column('tilemap_seed', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'tilemap_seed')
    op.drop_column('locations', 'grid_height')
    op.drop_column('locations', 'grid_width')
    # ### end Alembic commands ###
