"""add locations and resource deposits

Revision ID: 1ac9d284b10f
Revises: 70c22751ddf7
Create Date: 2026-01-24 14:59:48.503445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ac9d284b10f'
down_revision: Union[str, Sequence[str], None] = '70c22751ddf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('z', sa.Float(), nullable=False),
    sa.Column('biome', sa.String(), nullable=False),
    sa.Column('claimed_by_company_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claimed_by_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claimed_by_company_id')
    )
    op.create_table('resource_deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_deposits_location_id'), 'resource_deposits', ['location_id'], unique=False)
    op.drop_index(op.f('ix_market_trades_buyer_company_id'), table_name='market_trades')
    op.drop_index(op.f('ix_market_trades_good_id'), table_name='market_trades')
    op.drop_index(op.f('ix_market_trades_seller_company_id'), table_name='market_trades')
    op.drop_table('market_trades')
    op.add_column('companies', sa.Column('home_location_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['home_location_id'])
    op.create_foreign_key(None, 'companies', 'locations', ['home_location_id'], ['id'])
    op.drop_index(op.f('ix_inventories_company_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_good_id'), table_name='inventories')
    op.drop_constraint(op.f('uix_company_good'), 'inventories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_company_good'), 'inventories', ['company_id', 'good_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_inventories_good_id'), 'inventories', ['good_id'], unique=False)
    op.create_index(op.f('ix_inventories_company_id'), 'inventories', ['company_id'], unique=False)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'home_location_id')
    op.create_table('market_trades',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('good_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('buyer_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('seller_company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price_per_unit', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], name=op.f('market_trades_buyer_company_id_fkey')),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], name=op.f('market_trades_good_id_fkey')),
    sa.ForeignKeyConstraint(['seller_company_id'], ['companies.id'], name=op.f('market_trades_seller_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('market_trades_pkey'))
    )
    op.create_index(op.f('ix_market_trades_seller_company_id'), 'market_trades', ['seller_company_id'], unique=False)
    op.create_index(op.f('ix_market_trades_good_id'), 'market_trades', ['good_id'], unique=False)
    op.create_index(op.f('ix_market_trades_buyer_company_id'), 'market_trades', ['buyer_company_id'], unique=False)
    op.drop_index(op.f('ix_resource_deposits_location_id'), table_name='resource_deposits')
    op.drop_table('resource_deposits')
    op.drop_table('locations')
    # ### end Alembic commands ###
