"""Add total_resources column to Planet

Revision ID: 50b31553c4ae
Revises: 6ffb61dc9198
Create Date: 2026-01-26 14:24:17.844639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b31553c4ae'
down_revision: Union[str, Sequence[str], None] = '6ffb61dc9198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('total_resources', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planets', 'total_resources')
    # ### end Alembic commands ###
