"""Add x y z coordinates to regions

Revision ID: 6ffb61dc9198
Revises: efbf48dabaf6
Create Date: 2026-01-26 14:15:20.677393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffb61dc9198'
down_revision: Union[str, Sequence[str], None] = 'efbf48dabaf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('x', sa.Float(), nullable=False))
    op.add_column('regions', sa.Column('y', sa.Float(), nullable=False))
    op.add_column('regions', sa.Column('z', sa.Float(), nullable=False))
    
    # op.drop_column('star_systems', 'star_size')
    # op.drop_column('star_systems', 'star_luminosity')
    # op.drop_column('star_systems', 'star_temperature')
    # op.drop_column('star_systems', 'star_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('star_systems', sa.Column('star_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('star_systems', sa.Column('star_temperature', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('star_systems', sa.Column('star_luminosity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('star_systems', sa.Column('star_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('regions', 'z')
    op.drop_column('regions', 'y')
    op.drop_column('regions', 'x')
    # ### end Alembic commands ###
