"""add home_location to companies

Revision ID: 76b5019a459c
Revises: 71fc592c4d83
Create Date: 2026-01-24 15:57:01.152742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76b5019a459c'
down_revision: Union[str, Sequence[str], None] = '71fc592c4d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_constraint(op.f('uq_location_good_extraction'), 'extraction_sites', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_location_good_extraction'), 'extraction_sites', ['location_id', 'good_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    # ### end Alembic commands ###
