"""add inventories

Revision ID: 9ca0300aac27
Revises: 3a40ff64d851
Create Date: 2026-01-23 16:40:44.354656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca0300aac27'
down_revision: Union[str, Sequence[str], None] = '3a40ff64d851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'good_id', name='uix_company_good')
    )
    op.create_index(op.f('ix_inventories_company_id'), 'inventories', ['company_id'], unique=False)
    op.create_index(op.f('ix_inventories_good_id'), 'inventories', ['good_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventories_good_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_company_id'), table_name='inventories')
    op.drop_table('inventories')
    # ### end Alembic commands ###
