"""add production jobs

Revision ID: c901eef47485
Revises: 2baa7a240d3e
Create Date: 2026-01-23 16:58:28.484203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c901eef47485'
down_revision: Union[str, Sequence[str], None] = '2baa7a240d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('input_good_id', sa.Integer(), nullable=False),
    sa.Column('output_good_id', sa.Integer(), nullable=False),
    sa.Column('input_quantity', sa.Integer(), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finishes_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['input_good_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['output_good_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_jobs_company_id'), 'production_jobs', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_jobs_company_id'), table_name='production_jobs')
    op.drop_table('production_jobs')
    # ### end Alembic commands ###
