"""add production recipes

Revision ID: e7d2b022a702
Revises: c901eef47485
Create Date: 2026-01-23 17:12:48.783197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d2b022a702'
down_revision: Union[str, Sequence[str], None] = 'c901eef47485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_good_id', sa.Integer(), nullable=False),
    sa.Column('input_quantity', sa.Integer(), nullable=False),
    sa.Column('output_good_id', sa.Integer(), nullable=False),
    sa.Column('output_quantity', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['input_good_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['output_good_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_recipes_input_good_id'), 'production_recipes', ['input_good_id'], unique=False)
    op.create_index(op.f('ix_production_recipes_output_good_id'), 'production_recipes', ['output_good_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_recipes_output_good_id'), table_name='production_recipes')
    op.drop_index(op.f('ix_production_recipes_input_good_id'), table_name='production_recipes')
    op.drop_table('production_recipes')
    # ### end Alembic commands ###
