"""Register all tables

Revision ID: eb50d98f11df
Revises: initial_schema
Create Date: 2026-01-25 17:41:17.743966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb50d98f11df'
down_revision: Union[str, Sequence[str], None] = 'initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', postgresql.ENUM('processor', 'storage', 'spaceport', 'planetary_link', 'extractor_unit', 'extractor_head', 'command_center', name='buildingtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_id'), 'buildings', ['id'], unique=False)
    op.create_table('command_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_company_id', sa.Integer(), nullable=False),
    sa.Column('planet_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planetary_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', postgresql.ENUM('basic', 'advanced', 'hightech', name='processortier'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spaceports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extractor_heads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecu_id', sa.Integer(), nullable=False),
    sa.Column('extraction_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ecu_id'], ['ecus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractor_heads_id'), 'extractor_heads', ['id'], unique=False)
    op.drop_index(op.f('ix_extraction_sites_company_id'), table_name='extraction_sites')
    op.drop_index(op.f('ix_extraction_sites_good_id'), table_name='extraction_sites')
    op.drop_index(op.f('ix_extraction_sites_location_id'), table_name='extraction_sites')
    op.drop_table('extraction_sites')
    op.alter_column('productionrecipes', 'tier_in',
               existing_type=postgresql.ENUM('RAW', 'T1', 'T2', 'T3', 'T4', 'BASIC', 'ADVANCED', 'HIGHTECH', name='productiontier'),
               type_=sa.String(),
               nullable=True)
    op.alter_column('productionrecipes', 'tier_out',
               existing_type=postgresql.ENUM('RAW', 'T1', 'T2', 'T3', 'T4', 'BASIC', 'ADVANCED', 'HIGHTECH', name='productiontier'),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productionrecipes', 'tier_out',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RAW', 'T1', 'T2', 'T3', 'T4', 'BASIC', 'ADVANCED', 'HIGHTECH', name='productiontier'),
               nullable=False)
    op.alter_column('productionrecipes', 'tier_in',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RAW', 'T1', 'T2', 'T3', 'T4', 'BASIC', 'ADVANCED', 'HIGHTECH', name='productiontier'),
               nullable=False)
    op.create_table('extraction_sites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('good_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate_per_hour', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_extracted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('production_buffer', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('extraction_sites_company_id_fkey')),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], name=op.f('extraction_sites_good_id_fkey')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('extraction_sites_location_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('extraction_sites_pkey'))
    )
    op.create_index(op.f('ix_extraction_sites_location_id'), 'extraction_sites', ['location_id'], unique=False)
    op.create_index(op.f('ix_extraction_sites_good_id'), 'extraction_sites', ['good_id'], unique=False)
    op.create_index(op.f('ix_extraction_sites_company_id'), 'extraction_sites', ['company_id'], unique=False)
    op.drop_index(op.f('ix_extractor_heads_id'), table_name='extractor_heads')
    op.drop_table('extractor_heads')
    op.drop_table('storages')
    op.drop_table('spaceports')
    op.drop_table('processors')
    op.drop_table('planetary_links')
    op.drop_table('ecus')
    op.drop_table('command_centers')
    op.drop_index(op.f('ix_buildings_id'), table_name='buildings')
    op.drop_table('buildings')
    # ### end Alembic commands ###
